export const first20 = [
    { name: 'Ana Paula Weiss', team: 'Meu Check-List', perfil: 'Front-End' },
    { name: 'Anderson Quandt Venâncio', team: 'WMS Core', perfil: 'Back-End' },
    { name: 'Andre Felipe Moreira Leite', team: 'Meu Check-List', perfil: 'Back-End' },
    { name: 'Andre Luis Wisnheski', team: 'YMS', perfil: 'Back-End' },
    { name: 'Andre Luiz Custodio', team: 'Agendamento', perfil: 'Back-End' },
    { name: 'Andrei Dagoberto Streit', team: 'Agile Coach/Scrum Master', perfil: 'NA' },
    { name: 'Caio Malbug de Figueiredo', team: 'PO', perfil: 'NA' },
    { name: 'Daniel Lucas Avanço Alecrin', team: 'YMS', perfil: 'Back-End' },
    { name: 'Eduardo Filipe Gomes', team: 'Arquiteto', perfil: 'NA' },
    { name: 'Elias Michalczuk Ribeiro da Silva', team: 'YMS', perfil: 'Front-End' },
    { name: 'Elizabeth Santiago de Carvalho', team: 'Devops', perfil: 'NA' },
    { name: 'Ezequiel dos Santos', team: 'YMS', perfil: 'Back-End' },
    { name: 'Fabiano Faust', team: 'WMS Core', perfil: 'Back-End' },
    { name: 'Gabrieli Barbosa', team: 'WMS Operacional', perfil: 'Front-End' },
    { name: 'Guilherme Eduardo Bittencourt', team: 'Meu Check-List', perfil: 'Front-End' },
    { name: 'Guilherme Nass', team: 'Agendamento', perfil: 'Front-End' },
    { name: 'Gustavo Leandro Borges Silva', team: 'Agendamento', perfil: 'Back-End' },
    { name: 'Jackson Patrick Werka', team: 'WMS Operacional', perfil: 'Back-End' },
    { name: 'Jacson Marcelo Sell', team: 'Tribe Lead', perfil: 'NA' },
    { name: 'Jean Renato Kormann', team: 'Chapter', perfil: 'NA' }];

export const otherUsers = [
    { name: 'Joao Victor da Silva Fernandes', team: 'Agendamento', perfil: 'Back-End' },
    { name: 'Juliano Teofilo da Maia', team: 'MPO', perfil: 'NA' },
    { name: 'Leandro Conradi Zmovirzynski', team: 'WMS Operacional', perfil: 'Back-End' },
    { name: 'Lucas Frohlich', team: 'WMS Operacional', perfil: 'Back-End' },
    { name: 'Marcelo Souza', team: 'PO', perfil: 'NA' },
    { name: 'Marcos Pedro da Silveira', team: 'Agendamento', perfil: 'Back-End' },
    { name: 'Mateus Leal', team: 'WMS Core', perfil: 'Front-End' },
    { name: 'Morgana Creuz Ganske', team: 'UX', perfil: 'NA' },
    { name: 'Murilo Carlos Cardoso', team: 'Data Collection', perfil: 'Front-End' },
    { name: 'Natalia Maria Neves', team: 'A Definir', perfil: 'Front-End' },
    { name: 'Rafael Nunes', team: 'Meu Check-List', perfil: 'Back-End' },
    { name: 'Ruan Ricardo Salvador', team: 'Agendamento', perfil: 'Front-End' },
    { name: 'Siegklenes Rolland Beulke', team: 'Meu Check-List', perfil: 'Back-End' }];